// NoiseGenerator.compute
#pragma kernel CSMain

#include "Include/Noise.hlsl"

RWTexture2D<float4> NoiseTexture;
float Frequency;
float Threshold;
float Scale;
uint Width;
uint Height;
int Octaves;
float Persistence;
float Lacunarity;
bool IsBinary;
int Seed;
float Offset;

[numthreads(8,8,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
    float2 uv = (id.xy + float2(Offset, Offset));
    uv = float2((uv.x - Width / 2) / Scale, (uv.y - Height / 2) / Scale);
    float noiseValue = FBMValueNoise(
        uv,
        Frequency,
        Octaves,
        Persistence,
        Lacunarity,
        Seed
    );
    float4 color;

    if (IsBinary) {
        color = (noiseValue > Threshold) ? float4(1, 1, 1, 1) : float4(0, 0, 0, 1);
    } else {
        color = float4(noiseValue, noiseValue, noiseValue, 1);
    }

    NoiseTexture[id.xy] = color;
}
