#pragma kernel CSMain

#include "Include/Noise.hlsl"

RWTexture2D<float4> NoiseTexture;
RWStructuredBuffer<float> CurveData;
bool IsCurve;
float HeightMult;
float HeightAdd;
float LeftFrequency;
float RightFrequency;
int WorleyType;
bool WorleyFlip;
float Threshold;
float Weight;
float Scale;
uint Width;
uint Height;
int Octaves;
float Persistence;
float Lacunarity;
bool IsBinary;
int Seed;
float Offset;

[numthreads(8, 8, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
    if (id.x >= Width || id.y >= Height)
        return;
    float2 uv = IsCurve ? float2(id.x + Offset, (Height * 0.5) + Offset) : (id.xy + float2(Offset, Offset));
    uv = float2((uv.x - Width / 2) / Scale, (uv.y - Height / 2) / Scale);
    float noiseValue = MIXPerlinWorleyNoise(
        uv,
        LeftFrequency,
        RightFrequency,
        WorleyType,
        WorleyFlip,
        Weight,
        Octaves,
        Persistence,
        Lacunarity,
        Seed
    );
    
    if (IsCurve) {
        int curveValue = (int) floor(noiseValue * HeightMult + HeightAdd);
    
        CurveData[id.y * Width + id.x] = curveValue;
        OutputCurve(id, curveValue, Height, HeightMult, HeightAdd, NoiseTexture);

    } else {
        float4 color;
        if (IsBinary) {
            color = (noiseValue > Threshold) ? float4(1, 1, 1, 1) : float4(0, 0, 0, 1);
        } else {
            color = float4(noiseValue, noiseValue, noiseValue, 1);
        }
        
        NoiseTexture[id.xy] = color;
    }

}
