// NoiseGenerator.compute
#pragma kernel CSMain

#include "Include/Noise.hlsl"

RWTexture2D<float4> NoiseTexture;
uint Width;
uint Height;
float Frequency;
float Threshold;
bool IsBinary;
int Seed;
float Offset;
float Scale;

[numthreads(8,8,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{

    float2 offsetUv = (id.xy + float2(Offset, Offset));
    float2 scaleUv = float2((offsetUv.x - Width / 2) / Scale, (offsetUv.y - Height / 2) / Scale);
    float2 uv = scaleUv * Frequency + float2(Seed, Seed);
    
    float noiseValue = snoise(uv);
    
    float4 color;

    if (IsBinary){
        color = (noiseValue > Threshold) ? float4(1, 1, 1, 1) : float4(0, 0, 0, 1);
    } else {
        color = float4(noiseValue, noiseValue, noiseValue, 1);
    }

    NoiseTexture[id.xy] = color;
}





